const DRINK_CARDS = [
  {
    id: 1,
    name: "버번카운티 브랜드 스타우트 2019",
    abv: 15.2,
    imageUrl:
      "https://beer-api-prod.idkulab.com/media/drinks/bourbon-county-2019.png",
    category: "Beer",
    info: "밝은 옐로우 컬러에 상큼한 레몬 등의 푸릇한 과실향과 흰색 꽃향기가 풍성함. 매력포인트는 버터의 유질감과 스모키함이 어우러지는 부드러움.",
    origin: "뉴질랜드",
  },
  {
    id: 2,
    name: "버번카운티 브랜드 스타우트 2018",
    abv: 15.2,
    imageUrl:
      "https://beer-api-prod.idkulab.com/media/drinks/bourbon-county-2018.png",
    category: "Beer",
    info: "밝은 옐로우 컬러에 상큼한 레몬 등의 푸릇한 과실향과 흰색 꽃향기가 풍성함. 매력포인트는 버터의 유질감과 스모키함이 어우러지는 부드러움.",
    origin: "뉴질랜드",
  },
  {
    id: 3,
    name: "펑크 아이피에이",
    abv: 5.6,
    imageUrl:
      "https://beer-api-prod.idkulab.com/media/drinks/brewdong-punk-ipa.png",
    category: "Beer",
    info: "밝은 옐로우 컬러에 상큼한 레몬 등의 푸릇한 과실향과 흰색 꽃향기가 풍성함. 매력포인트는 버터의 유질감과 스모키함이 어우러지는 부드러움.",
    origin: "뉴질랜드",
  },
  {
    id: 4,
    name: "구스아일랜드 아이피에이",
    abv: 5.9,
    imageUrl: "https://beer-api-prod.idkulab.com/media/drinks/goose-ipa.png",
    category: "Beer",
    info: "밝은 옐로우 컬러에 상큼한 레몬 등의 푸릇한 과실향과 흰색 꽃향기가 풍성함. 매력포인트는 버터의 유질감과 스모키함이 어우러지는 부드러움.",
    origin: "뉴질랜드",
  },
  {
    id: 5,
    name: "구스아일랜드 312 얼반위트",
    abv: 4.2,
    imageUrl: "https://beer-api-prod.idkulab.com/media/drinks/goose-312.png",
    category: "Beer",
    info: "밝은 옐로우 컬러에 상큼한 레몬 등의 푸릇한 과실향과 흰색 꽃향기가 풍성함. 매력포인트는 버터의 유질감과 스모키함이 어우러지는 부드러움.",
    origin: "뉴질랜드",
  },
  {
    id: 6,
    name: "어반래빗 바이젠",
    abv: 5,
    imageUrl:
      "https://beer-api-prod.idkulab.com/media/drinks/urban-rabbit-weizen.png",
    category: "Beer",
    info: "밝은 옐로우 컬러에 상큼한 레몬 등의 푸릇한 과실향과 흰색 꽃향기가 풍성함. 매력포인트는 버터의 유질감과 스모키함이 어우러지는 부드러움.",
    origin: "뉴질랜드",
  },
  {
    id: 7,
    name: "어반래빗 라거",
    abv: 5,
    imageUrl:
      "https://beer-api-prod.idkulab.com/media/drinks/urban-rabbit-lager.png",
    category: "Beer",
    info: "밝은 옐로우 컬러에 상큼한 레몬 등의 푸릇한 과실향과 흰색 꽃향기가 풍성함. 매력포인트는 버터의 유질감과 스모키함이 어우러지는 부드러움.",
    origin: "뉴질랜드",
  },
  {
    id: 8,
    name: "구미호 피치에일",
    abv: 4.5,
    imageUrl:
      "https://beer-api-prod.idkulab.com/media/drinks/gumiho-peach-ale.png",
    category: "Beer",
    info: "밝은 옐로우 컬러에 상큼한 레몬 등의 푸릇한 과실향과 흰색 꽃향기가 풍성함. 매력포인트는 버터의 유질감과 스모키함이 어우러지는 부드러움.",
    origin: "뉴질랜드",
  },
  {
    id: 9,
    name: "핸드앤몰트 상상 페일 에일",
    abv: 5.1,
    imageUrl:
      "https://beer-api-prod.idkulab.com/media/drinks/hand-and-malt-pale-ale.png",
    category: "Beer",
    info: "밝은 옐로우 컬러에 상큼한 레몬 등의 푸릇한 과실향과 흰색 꽃향기가 풍성함. 매력포인트는 버터의 유질감과 스모키함이 어우러지는 부드러움.",
    origin: "뉴질랜드",
  },
  {
    id: 10,
    name: "강서 마일드 에일",
    abv: 4.6,
    imageUrl: "https://beer-api-prod.idkulab.com/media/drinks/gangseo.png",
    category: "Beer",
    info: "밝은 옐로우 컬러에 상큼한 레몬 등의 푸릇한 과실향과 흰색 꽃향기가 풍성함. 매력포인트는 버터의 유질감과 스모키함이 어우러지는 부드러움.",
    origin: "뉴질랜드",
  },
  {
    id: 11,
    name: "세븐브로이 곰표 밀맥주",
    abv: 4.5,
    imageUrl:
      "https://zuzu-resource.s3.ap-northeast-2.amazonaws.com/drinks-category/category_etc.png",
    info: "밝은 옐로우 컬러에 상큼한 레몬 등의 푸릇한 과실향과 흰색 꽃향기가 풍성함. 매력포인트는 버터의 유질감과 스모키함이 어우러지는 부드러움.",
    origin: "뉴질랜드",
    category: "Beer",
  },
  {
    id: 12,
    name: "한강 에일",
    abv: 5.2,
    imageUrl: "https://beer-api-prod.idkulab.com/media/drinks/hangang.png",
    category: "Beer",
    info: "밝은 옐로우 컬러에 상큼한 레몬 등의 푸릇한 과실향과 흰색 꽃향기가 풍성함. 매력포인트는 버터의 유질감과 스모키함이 어우러지는 부드러움.",
    origin: "뉴질랜드",
  },
  {
    id: 13,
    name: "서울 에일",
    abv: 5,
    imageUrl:
      "https://zuzu-resource.s3.ap-northeast-2.amazonaws.com/drinks-category/category_etc.png",
    info: "밝은 옐로우 컬러에 상큼한 레몬 등의 푸릇한 과실향과 흰색 꽃향기가 풍성함. 매력포인트는 버터의 유질감과 스모키함이 어우러지는 부드러움.",
    origin: "뉴질랜드",
    category: "Beer",
  },
  {
    id: 14,
    name: "양평 에일",
    abv: 4.5,
    imageUrl:
      "https://zuzu-resource.s3.ap-northeast-2.amazonaws.com/drinks-category/category_etc.png",
    info: "밝은 옐로우 컬러에 상큼한 레몬 등의 푸릇한 과실향과 흰색 꽃향기가 풍성함. 매력포인트는 버터의 유질감과 스모키함이 어우러지는 부드러움.",
    origin: "뉴질랜드",
    category: "Beer",
  },
  {
    id: 15,
    name: "독립 에일",
    abv: 6,
    imageUrl:
      "https://zuzu-resource.s3.ap-northeast-2.amazonaws.com/drinks-category/category_etc.png",
    category: "Beer",
    info: "밝은 옐로우 컬러에 상큼한 레몬 등의 푸릇한 과실향과 흰색 꽃향기가 풍성함. 매력포인트는 버터의 유질감과 스모키함이 어우러지는 부드러움.",
    origin: "뉴질랜드",
  },
  {
    id: 16,
    name: "코리아 페일 에일",
    abv: 4.6,
    imageUrl:
      "https://zuzu-resource.s3.ap-northeast-2.amazonaws.com/drinks-category/category_etc.png",
    info: "밝은 옐로우 컬러에 상큼한 레몬 등의 푸릇한 과실향과 흰색 꽃향기가 풍성함. 매력포인트는 버터의 유질감과 스모키함이 어우러지는 부드러움.",
    origin: "뉴질랜드",
    category: "Beer",
  },
  {
    id: 17,
    name: "서초",
    abv: 4.2,
    imageUrl:
      "https://zuzu-resource.s3.ap-northeast-2.amazonaws.com/drinks-category/category_etc.png",
    info: "밝은 옐로우 컬러에 상큼한 레몬 등의 푸릇한 과실향과 흰색 꽃향기가 풍성함. 매력포인트는 버터의 유질감과 스모키함이 어우러지는 부드러움.",
    origin: "뉴질랜드",
    category: "Beer",
  },
  {
    id: 18,
    name: "맥아더",
    abv: 4.7,
    imageUrl: "https://beer-api-prod.idkulab.com/media/drinks/mac-a-the.png",
    category: "Beer",
    info: "밝은 옐로우 컬러에 상큼한 레몬 등의 푸릇한 과실향과 흰색 꽃향기가 풍성함. 매력포인트는 버터의 유질감과 스모키함이 어우러지는 부드러움.",
    origin: "뉴질랜드",
  },
  {
    id: 19,
    name: "흥청망청",
    abv: 5,
    imageUrl:
      "https://beer-api-prod.idkulab.com/media/drinks/heung-chung-mang-chung.png",
    category: "Beer",
    info: "밝은 옐로우 컬러에 상큼한 레몬 등의 푸릇한 과실향과 흰색 꽃향기가 풍성함. 매력포인트는 버터의 유질감과 스모키함이 어우러지는 부드러움.",
    origin: "뉴질랜드",
  },
  {
    id: 20,
    name: "레오",
    abv: 5,
    imageUrl: "https://beer-api-prod.idkulab.com/media/drinks/leo.png",
    category: "Beer",
    info: "밝은 옐로우 컬러에 상큼한 레몬 등의 푸릇한 과실향과 흰색 꽃향기가 풍성함. 매력포인트는 버터의 유질감과 스모키함이 어우러지는 부드러움.",
    origin: "뉴질랜드",
  },
  {
    id: 21,
    name: "빅 드랍 밀크 스타우트",
    abv: 0.5,
    imageUrl:
      "https://beer-api-prod.idkulab.com/media/drinks/big_drop_galactic_milk_stout.png",
    category: "Beer",
    info: "밝은 옐로우 컬러에 상큼한 레몬 등의 푸릇한 과실향과 흰색 꽃향기가 풍성함. 매력포인트는 버터의 유질감과 스모키함이 어우러지는 부드러움.",
    origin: "뉴질랜드",
  },
  {
    id: 22,
    name: "가펠 패스브라우저 사과 나투르트륍",
    abv: 0,
    imageUrl:
      "https://beer-api-prod.idkulab.com/media/drinks/gaffel_frassbrause.png",
    category: "Beer",
    info: "밝은 옐로우 컬러에 상큼한 레몬 등의 푸릇한 과실향과 흰색 꽃향기가 풍성함. 매력포인트는 버터의 유질감과 스모키함이 어우러지는 부드러움.",
    origin: "뉴질랜드",
  },
  {
    id: 23,
    name: "에스트렐라 갈리시아 오리지널",
    abv: 0,
    imageUrl:
      "https://beer-api-prod.idkulab.com/media/drinks/estrella_galicia.png",
    category: "Beer",
    info: "밝은 옐로우 컬러에 상큼한 레몬 등의 푸릇한 과실향과 흰색 꽃향기가 풍성함. 매력포인트는 버터의 유질감과 스모키함이 어우러지는 부드러움.",
    origin: "뉴질랜드",
  },
  {
    id: 24,
    name: "에스트렐라 갈리시아 토스타다",
    abv: 0,
    imageUrl:
      "https://beer-api-prod.idkulab.com/media/drinks/estrella_galicia_tostada.png",
    category: "Beer",
    info: "밝은 옐로우 컬러에 상큼한 레몬 등의 푸릇한 과실향과 흰색 꽃향기가 풍성함. 매력포인트는 버터의 유질감과 스모키함이 어우러지는 부드러움.",
    origin: "뉴질랜드",
  },
  {
    id: 25,
    name: "구미호 릴렉스 비어",
    abv: 4.2,
    imageUrl:
      "https://beer-api-prod.idkulab.com/media/drinks/kumiho_relax_beer.png",
    category: "Beer",
    info: "밝은 옐로우 컬러에 상큼한 레몬 등의 푸릇한 과실향과 흰색 꽃향기가 풍성함. 매력포인트는 버터의 유질감과 스모키함이 어우러지는 부드러움.",
    origin: "뉴질랜드",
  },
  {
    id: 26,
    name: "슈퍼 아이피에이",
    abv: 6.4,
    imageUrl:
      "https://beer-api-prod.idkulab.com/media/drinks/craftbros_super_ipa.png",
    category: "Beer",
    info: "밝은 옐로우 컬러에 상큼한 레몬 등의 푸릇한 과실향과 흰색 꽃향기가 풍성함. 매력포인트는 버터의 유질감과 스모키함이 어우러지는 부드러움.",
    origin: "뉴질랜드",
  },
  {
    id: 27,
    name: "흑백 임페리얼 스타우트",
    abv: 10,
    imageUrl:
      "https://beer-api-prod.idkulab.com/media/drinks/hukbaek_imperial_stout.png",
    category: "Beer",
    info: "밝은 옐로우 컬러에 상큼한 레몬 등의 푸릇한 과실향과 흰색 꽃향기가 풍성함. 매력포인트는 버터의 유질감과 스모키함이 어우러지는 부드러움.",
    origin: "뉴질랜드",
  },
  {
    id: 28,
    name: "콩도 시나몬롤 임페리얼 스타우트",
    abv: 12,
    imageUrl: "https://beer-api-prod.idkulab.com/media/drinks/kong_island.png",
    category: "Beer",
    info: "밝은 옐로우 컬러에 상큼한 레몬 등의 푸릇한 과실향과 흰색 꽃향기가 풍성함. 매력포인트는 버터의 유질감과 스모키함이 어우러지는 부드러움.",
    origin: "뉴질랜드",
  },
  {
    id: 29,
    name: "우리쌀 라거",
    abv: 5,
    imageUrl:
      "https://beer-api-prod.idkulab.com/media/drinks/woori_ssal_lager.png",
    category: "Beer",
    info: "밝은 옐로우 컬러에 상큼한 레몬 등의 푸릇한 과실향과 흰색 꽃향기가 풍성함. 매력포인트는 버터의 유질감과 스모키함이 어우러지는 부드러움.",
    origin: "뉴질랜드",
  },
  {
    id: 30,
    name: "처용 IPL",
    abv: 5,
    imageUrl: "https://beer-api-prod.idkulab.com/media/drinks/cheoyong_ipl.png",
    category: "Beer",
    info: "밝은 옐로우 컬러에 상큼한 레몬 등의 푸릇한 과실향과 흰색 꽃향기가 풍성함. 매력포인트는 버터의 유질감과 스모키함이 어우러지는 부드러움.",
    origin: "뉴질랜드",
  },
  {
    id: 31,
    name: "T-둔켈",
    abv: 4.5,
    imageUrl: "https://beer-api-prod.idkulab.com/media/drinks/t_dunkel.png",
    category: "Beer",
    info: "밝은 옐로우 컬러에 상큼한 레몬 등의 푸릇한 과실향과 흰색 꽃향기가 풍성함. 매력포인트는 버터의 유질감과 스모키함이 어우러지는 부드러움.",
    origin: "뉴질랜드",
  },
  {
    id: 32,
    name: "T-바이젠",
    abv: 4.5,
    imageUrl: "https://beer-api-prod.idkulab.com/media/drinks/t_weizen.png",
    category: "Beer",
    info: "밝은 옐로우 컬러에 상큼한 레몬 등의 푸릇한 과실향과 흰색 꽃향기가 풍성함. 매력포인트는 버터의 유질감과 스모키함이 어우러지는 부드러움.",
    origin: "뉴질랜드",
  },
];

export { DRINK_CARDS };
